### ISSUE TITLE
[疑问]显示映射表加载成功后，实际游戏内容并未发生替换。

### ISSUE THREAD

**Issue by TUsama** [LuZWCHA/DynTranslation#1]
我不太确定这个是bug，或者只是纯粹的我操作失误了。若是后者，我对打扰你感到万分抱歉。

工作背景为：
1. 游戏版本 1.15.2；forge 31.2.57
2. 模组版本 1.3.2；前置 MixinBootstrap 1.1.0
3. 并未安装其他模组与资源包

我在使用模组的过程中，在 dyntranslation_default.json 构造了如下的映射表：
``
{
"*":{
	"金矿石" : "金闪闪",
	"1":"2"
  }
}
``
然后在游戏中加载映射。游戏显示加载成功，共 2 条映射被加载，但检查金矿石的文本后发现，金矿石并未被替换，以下为图片：

[![b3towR.png](https://s4.ax1x.com/2022/03/02/b3towR.png)](https://imgtu.com/i/b3towR)

[![b3Nm0s.png](https://s4.ax1x.com/2022/03/02/b3Nm0s.png)](https://imgtu.com/i/b3Nm0s)

**Comment by LuZWCHA** [comment]
未能复现，暂时关闭。
